import Config

config :koe_frame,
  media_staging_root: Path.join(File.cwd!(), ".koe_frame-dev-staging")

config :koe_frame,
  transcript_review_tenant_id: System.get_env("KOE_FRAME_TENANT_ID"),
  speaches_base_url: System.get_env("KOE_FRAME_SPEACHES_BASE_URL"),
  speaches_model:
    System.get_env("KOE_FRAME_SPEACHES_MODEL", "deepdml/faster-whisper-large-v3-turbo-ct2"),
  speaches_timeout_ms: System.get_env("KOE_FRAME_SPEACHES_TIMEOUT_MS", "180000"),
  subtitler_cue_base_url: System.get_env("SUBTITLER_CUE_BASE_URL"),
  subtitler_cue_token_ref: System.get_env("SUBTITLER_CUE_TOKEN_REF"),
  subtitler_cue_timeout_ms: String.to_integer(System.get_env("SUBTITLER_CUE_TIMEOUT_MS", "30000"))

# Configure your database
config :koe_frame, Defdo.KoeFrame.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "koe_frame_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :koe_frame, Defdo.KoeFrameWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: String.duplicate("0", 64),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:koe_frame, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:koe_frame, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :koe_frame, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
